### ISSUE TITLE
Apostrophe question

### ISSUE THREAD

**Issue by ole** [frankrausch/Typographizer#6]
Hi @frankrausch, I was wondering if you had seen this 2015 article titled [Which Unicode character should represent the English apostrophe? (And why the Unicode committee is very wrong.)](https://tedclancy.wordpress.com/2015/06/03/which-unicode-character-should-represent-the-english-apostrophe-and-why-the-unicode-committee-is-very-wrong/) and what you think about it.

In the article, the author argues that writing the apostrophe with a U+2019 (RIGHT SINGLE QUOTATION MARK, `"’"`), despite being form recommended by the Unicode standard, is wrong and that U+02BC (MODIFIER LETTER APOSTROPHE, `"ʼ"`) would be the semantically better choice.

To be clear, I’m not saying that Typographizer should switch from U+2019 to U+02BC because a general-purpose library like this should adhere to the standard if possible. I’m simply wondering what you think about this.

Feel free to close this issue.

**Comment by frankrausch** [comment]
Hi @ole, thanks for this interesting perspective!

I do think that this article brings up some valid points, especially the problem that—if you follow the recommendations—one code point is used for two very different purposes, which is, well, not ideal.

But using deviating from common industry conventions just to do something “semantically right” is especially dangerous if you don’t even see the difference, because the two marks *look* identical. Non-breaking space in source code, anyone?

Also I’m pretty confident that an apostrophe is not a modifier letter. An apostrophe is punctuation; it doesn’t change the meaning of a letter or a word, but is a stand-in for skipped letters.
If you use an em dash for a similar same purpose, would it become a modifier, too? I don’t think so. Example: “I don’t believe this bull—”

Lastly, I’m not sure if the MODIFIER LETTER APOSTROPHE will be rendered with the correct glyph in all operating systems, layout engines, etc. I’m not even sure if it is meant to be used as an apostrophe, or if it modifies the previous letter for certain languages, like a diacritic. Haven’t done any research on this though, it’s a hunch. :)

Closing the issue, thanks!

**Comment by ole** [comment]
Thanks for the thoughtful reply. I agree!
